// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { defineConfig } from "prisma/config";
import { loadLocalEnv } from "./prisma/local-env";

// Never `dotenv/config`: this project has no development or staging Supabase, so
// `.env` is the shared PRODUCTION instance. Loading `.env.local` here means the
// accidental path is gone; a deliberate remote run must export DATABASE_URL and
// DIRECT_URL explicitly (see section 6.5 of the v2 SDD for the promotion step).
loadLocalEnv();

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // CLI migrations use the session-mode pooler (DIRECT_URL); the app runtime
    // uses the transaction-mode pooler (DATABASE_URL) via src/lib/db.ts.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
